    - name: Install MySQL database
      yum:
        name: "{{ item }}"
        state: present
        with_items:
          - mysql-server
          - mysql-devel
      
    - name: Start the Database service
      service: 
        name: mysql
        state: started
        enabled: yes

    - name: Create Database
      mysql_db:
        name: "{{ db_name }}"
        state: present
    
    - name: Create a Database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'